{
  "version": 2.1,
  "jobs": {
  "build": {
  "docker": [
    {
    "image": "cimg/python:3.10-browsers"
    }
  ],
  "working_directory": "~/repo",
  "steps": [
    "checkout",
    {
    "run": {
    "name": "install dependencies",
    "command": "python3 -m venv venv && venv/bin/python -m pip install --upgrade pip && venv/bin/python -m pip install -r requirements.txt"
    }
    },
    {
    "run": {
    "name": "run test",
    "command": "venv/bin/python -m pytest test_practiice2.py -v --junit-xml=test-results/regression/results.xml"
    }
    },
    {
    "store_test_results": {
    "path": "test-results"
    }
    }
  ]
  }
  },
  "workflows": {
  "test-workflow": {
  "jobs": [
    "build"
  ]
  }
  }
}

